{% set name = "liblie-group-controllers" %}
{% set version = "0.3.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/ami-iit/lie-group-controllers/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 964e062dc726e92bfa7552bf3f390f65a46531d385897815cc55d04bc18f9ccc

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - cmake
    - pkg-config
    - ninja
  host:
    - eigen
    - manif
    - catch2 2
  run:
    - eigen
    - manif

test:
  commands:
    - test -f $PREFIX/include/LieGroupControllers/ProportionalDerivativeController.h  # [unix]
    - if not exist %LIBRARY_INC%\\LieGroupControllers\\ProportionalDerivativeController.h exit 1  # [win]

about:
  home: https://github.com/ami-iit/lie-group-controllers
  license: LGPL-2.1-or-later
  license_file: LICENSE
  summary: Header-only C++ library containing controllers designed for Lie Groups.

extra:
  recipe-maintainers:
    - traversaro
